#Group Productos Usuarios
## Todos los productos [/productos]
### Listado de todos los productos [GET]

+ Request 200
    Location : /productos

+ Response 200 (application/json)
    [
        {
            status : 'ok',
            data : [
                {
                    id_p : 2,
                    nombre_p : "vino",
                    descripcion_p : "vino descripcion",
                    precio_p : 270.23,
                    stock_p : 123123,
                    imagen_p : '/images/foto.jpg'
                }
            ]
        }
    ]

## Producto individual [/productos/1]
### Listado de producto individual [GET]
+ Request 200
    Location : productos/1

+ Response 200 (application/json)
    + Body 
        {
            nombre_p : 'Vino',
            precio_p : 4123.2,
            stock_p : 12,
            descripcion_p : "vino de calidad",
            imagen_p : "images/foto.jpg"
        }
+ Response 500 (application/json)
    + Body
        {
            status : 'error'
        }

#Group Productos Admin
## Alta de productos [/productosAdmin]
### Insetar un nuevo producto [POST]

+ Request 200 (application/json)
    + Body
        {
           
            nombre_p : "vino",
            descripcion_p : "vino descripcion",
            precio_p : 270.23,
            stock_p : 123123,
            imagen_p : '/images/foto.jpg'
        }
+ Response 200 (application/json)
    + Body 
        {
            status : 'ok'
            id_p : 4
        }